Rocky.Server/Controllers/CartController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky.DataAccess.Repositories.AppUser;
using Rocky.DataAccess.Repositories.Inquiry;
using Rocky.DataAccess.Repositories.Product;
using Rocky.Models;
using Rocky.Models.Cart;
using Rocky.Models.Inquiry;
using Rocky.Utility;

namespace Rocky.Server.Controllers;

[Authorize]
public class CartController : Controller
{
    private readonly ILogger<CartController> _logger;
    private readonly IAppUserRepository _repoAppUser;
    private readonly IProductRepository _repoProduct;
    private readonly IInquiryHeaderRepository _repoInquiryHeader;
    private readonly IInquiryDetailRepository _repoInquiryDetail;

    public CartController(
        ILogger<CartController> logger,
        IAppUserRepository repoAppUser,
        IProductRepository repoProduct,
        IInquiryHeaderRepository repoInquiryHeader,
        IInquiryDetailRepository repoInquiryDetail)
    {
        _logger = logger;
        _repoAppUser = repoAppUser;
        _repoProduct = repoProduct;
        _repoInquiryHeader = repoInquiryHeader;
        _repoInquiryDetail = repoInquiryDetail;
    }

    #region Index

    public IActionResult Index()
    {
        var sessionCart = GetSessionCart
            ?.ToList() ?? new();
        var model = new List<CartIndexModel>();

        foreach (var cart in sessionCart)
        {
            var product = _repoProduct.Find(cart.ProductId);
            if (product == null) continue;

            model.Add(new CartIndexModel
            {
                Product = product,
                SqFt = cart.SqFt
            });
        }
        
        return View(model);
    }

    public IActionResult RemoveFromCart(int id)
    {
        var sessionCart = GetSessionCart;
        var product = sessionCart
            ?.FirstOrDefault(p => p.ProductId == id);

        if (product != null)
        {
            sessionCart!.Remove(product);
            HttpContext.Session.Set(Const.SessionCartList, sessionCart);
            TempData[Const.Success] = "Item successfully removed from cart";

            if (sessionCart.Any() is false)
                return RedirectToAction("Index", "Home");
        }
        else if (product == null)
            TempData[Const.Error] = "Error removing item from cart";

        return RedirectToAction(nameof(Index));
    }

    #endregion Index

    #region Summary

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Summary(IList<CartIndexModel> modelIn)
    {
        var sessionCart = new List<ShoppingCart>();
        foreach (var item in modelIn)
        {
            var product = _repoProduct.Find(item.Product!.Id);
            if (product == null) continue;
            item.Product = product;

            var sqft = item.SqFt is > 0 and <= 10_000 ? item.SqFt : 1;
            item.SqFt = sqft;

            sessionCart.Add(new ShoppingCart
            {
                ProductId = product.Id,
                SqFt = sqft
            });
        }
        HttpContext.Session.Set(Const.SessionCartList, sessionCart);

        if (modelIn.Any() is false)
        {
            TempData[Const.Error] = "Order generation error";
            return RedirectToAction(nameof(Index));
        }

        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var modelOut = new CartSummaryModel
        {
            AppAppUser = _repoAppUser.Find(userId) 
                         ?? new AppUserDTO(),
            ItemCollection = modelIn
        };

        return View(modelOut);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult SummaryPost(CartSummaryModel model)
    {
        var inquiryHeader = new InquiryHeaderDTO
        {
            AppUserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
            FullName = model.AppAppUser.FullName,
            PhoneNumber = model.AppAppUser.PhoneNumber,
            Email = model.AppAppUser.Email,
            Date = DateTime.Now
        };
        _repoInquiryHeader.Add(inquiryHeader);
        _repoInquiryHeader.SaveChanges();

        foreach (var item in model.ItemCollection!)
            _repoInquiryDetail.Add(new InquiryDetailDTO
            {
                InquiryHeaderId = inquiryHeader.Id,
                ProductId = item.Product!.Id,
                SqFt = item.SqFt
            });

        _repoInquiryDetail.SaveChanges();
        HttpContext.Session.Clear();

        TempData[Const.Success] = "Order created successfully";
        return RedirectToAction("Index", "Home");
    }

    #endregion Summary

    #region Update

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Update(IList<CartIndexModel> modelIn)
    {
        var sessionCart = new List<ShoppingCart>();
        sessionCart.AddRange(modelIn.Select(item => new ShoppingCart
        {
            ProductId = item.Product!.Id,
            SqFt = item.SqFt is > 0 and <= 10_000 ? item.SqFt : 1
        }));
        HttpContext.Session.Set(Const.SessionCartList, sessionCart);

        if (modelIn.Any() is false)
            TempData[Const.Error] = "Error while cart update";
        else TempData[Const.Success] = "Cart updated successfully";

        return RedirectToAction(nameof(Index));
    }

    #endregion Update

    #region ControllerHelpers

    private List<ShoppingCart>? GetSessionCart =>
        HttpContext.Session.Get<List<ShoppingCart>>(Const.SessionCartList);

    #endregion ControllerHelpers
}

Rocky.Server/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky.DataAccess.Repositories.Category;
using Rocky.Models.Category;
using Rocky.Utility;

namespace Rocky.Server.Controllers;

[Authorize(Roles = Const.AdminRole)]
public class CategoryController : Controller
{
    private readonly ILogger<CategoryController> _logger;
    private readonly ICategoryRepository _repoCategory;

    public CategoryController(ILogger<CategoryController> logger, ICategoryRepository repoCategory)
    {
        _logger = logger;
        _repoCategory = repoCategory;
    }

    #region Index

    public IActionResult Index()
    {
        var items = _repoCategory.GetAll();
        return View(items);
    }

    #endregion Index

    #region Create

    public IActionResult Create() => View();

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Create(CategoryDTO model)
    {
        if (ModelState.IsValid is false)
        {
            TempData[Const.Error] = "Error while creating category";
            return View(model);
        }

        _repoCategory.Add(model);
        _repoCategory.SaveChanges();

        TempData[Const.Success] = "Category created successfully";
        return RedirectToAction(nameof(Index));
    }

    #endregion Create

    #region Edit

    public IActionResult Edit(int? id)
    {
        if (id is null or 0)
            return NotFound();

        var model = _repoCategory.Find(id);
        if (model == null)
            return NotFound();

        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Edit(CategoryDTO model)
    {
        if (ModelState.IsValid is false)
        {
            TempData[Const.Error] = "Error while editing category";
            return View(model);
        }

        _repoCategory.Update(model);
        _repoCategory.SaveChanges();

        TempData[Const.Success] = "Category edited successfully";
        return RedirectToAction(nameof(Index));
    }

    #endregion Edit

    #region Delete

    public IActionResult Delete(int? id)
    {
        if (id is null or 0)
            return NotFound();

        var model = _repoCategory.Find(id);
        if (model == null)
            return NotFound();

        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        if (id is null or 0)
            return NotFound();

        var model = _repoCategory.Find(id);
        if (model == null)
            return NotFound();

        _repoCategory.Remove(model);
        _repoCategory.SaveChanges();

        TempData[Const.Success] = "Category deleted successfully";
        return RedirectToAction(nameof(Index));
    }

    #endregion Delete
}

Rocky.Server/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky.DataAccess.Repositories.Inquiry;
using Rocky.Models;
using Rocky.Models.Inquiry;
using Rocky.Utility;
using Const = Rocky.Utility.Const;

namespace Rocky.Server.Controllers;

[Authorize(Roles = Const.AdminRole)]
public class InquiryController : Controller
{
    private readonly IInquiryHeaderRepository _repoInquiryHeader;
    private readonly IInquiryDetailRepository _repoInquiryDetail;

    public InquiryController(IInquiryHeaderRepository repoInquiryHeader, IInquiryDetailRepository repoInquiryDetail)
    {
        _repoInquiryHeader = repoInquiryHeader;
        _repoInquiryDetail = repoInquiryDetail;
    }

    #region Api

    public IActionResult GetInquiryList() =>
        Json(new { data = _repoInquiryHeader.GetAll() });

    #endregion Api

    #region Index

    public IActionResult Index() => View();

    #endregion Index

    #region Details

    public IActionResult Details(int id)
    {
        var header = _repoInquiryHeader.Find(id);
        if (header == null) return NotFound();

        return View(new InquiryDetailsModel
        {
            InquiryHeader = header,
            InquiryDetails = GetDetailByHeaderId(id)
        });
    }

    [HttpPost] [ValidateAntiForgeryToken]
    public IActionResult Details(InquiryDetailsModel model)
    {
        if (ModelState.IsValid is false)
        {
            TempData[Const.Error] = "Error converting to cart";
            return View(model);
        }

        model.InquiryDetails = GetDetailByHeaderId(model.InquiryHeader!.Id);

        HttpContext.Session.Clear();
        HttpContext.Session.Set(Const.SessionInquiryId, model.InquiryHeader.Id);
        HttpContext.Session.Set(Const.SessionCartList,
            model.InquiryDetails
                .Select(m => new ShoppingCart
                {
                    ProductId = m.ProductId,
                    SqFt = m.SqFt,
                })
                .ToList());

        TempData[Const.Success] = "Order converted to cart successfully";
        return RedirectToAction("Index", "Cart");
    }

    #region DetailsHerpers

    IEnumerable<InquiryDetailDTO> GetDetailByHeaderId(int id) =>
        _repoInquiryDetail.GetAll(m => m.InquiryHeaderId == id,
            include: nameof(InquiryDetailDTO.Product));

    #endregion DetailsHerpers

    #endregion Details

    #region Delete

    [HttpPost] [ValidateAntiForgeryToken]
    public IActionResult Delete(InquiryDetailsModel model)
    {
        var header = (_repoInquiryHeader.Find(model.InquiryHeader!.Id));
        if (header == null) return NotFound();

        model.InquiryDetails = GetDetailByHeaderId(model.InquiryHeader!.Id);
        _repoInquiryHeader.Remove(header);
        _repoInquiryDetail.RemoveRange(model.InquiryDetails);

        _repoInquiryHeader.SaveChanges();
        TempData[Const.Success] = "Order removed successfully";
        return RedirectToAction(nameof(Index));
    }

    #endregion Delete
}

Rocky.Server/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky.DataAccess.Repositories.Product;
using Rocky.Models.Product;
using Rocky.Utility;

namespace Rocky.Server.Controllers;

[Authorize(Roles = Const.AdminRole)]
public class ProductController : Controller
{
    private readonly ILogger<ProductController> _logger;
    private readonly IProductRepository _repoProduct;
    private readonly IWebHostEnvironment _env;

    public ProductController(
        ILogger<ProductController> logger,
        IProductRepository repoProduct,
        IWebHostEnvironment env)
    {
        _logger = logger;
        _repoProduct = repoProduct;
        _env = env;
    }

    #region Index

    public IActionResult Index()
    {
        var model = _repoProduct
            .GetAll(include: nameof(ProductDTO.Category));

        return View(model);
    }

    #endregion Index

    #region Upsert

    public IActionResult Upsert(int? id)
    {
        var model = new ProductUpsertModel
        {
            Product = id != null
                ? _repoProduct.Find(id)
                : new ProductDTO(),
        };
        if (model.Product == null)
            return NotFound();

        model.CategoryList = _repoProduct.GetCategoryDropDown();
        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductUpsertModel model)
    {
        if (ModelState.IsValid is false)
        {
            model.CategoryList ??= _repoProduct.GetCategoryDropDown();
            TempData[Const.Error] = "Validation error";
            return View(model);
        }

        var isUpdate = model.Product!.Id != 0;
        var file = HttpContext.Request.Form.Files
            .FirstOrDefault();

        if (isUpdate)
        {
            var dbProduct = _repoProduct
                .FirstOrDefault(p => p.Id == model.Product.Id, isTracking: false);
            if (dbProduct == null)
                return NotFound();

            if (file != null)
            {
                RemoveImage(dbProduct.Image!);
                UpsertImage(model.Product, file);
            }
            else model.Product.Image = dbProduct.Image;

            _repoProduct.Update(model.Product);
            TempData[Const.Success] = "Product edited successfully";
        }
        else
        {
            UpsertImage(model.Product, file!);
            _repoProduct.Add(model.Product);
            TempData[Const.Success] = "Product created successfully";
        }
        _repoProduct.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    #region UpsertHelpers

    private void UpsertImage(ProductDTO product, IFormFile file)
    {
        var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
        product.Image = fileName;

        var upload = string.Concat(_env.WebRootPath, Const.ProductImages, fileName);
        using var fs = new FileStream(upload, FileMode.Create);
        file.CopyTo(fs);
    }

    #endregion UpsertHelpers

    #endregion Upsert

    #region Delete

    public IActionResult Delete(int? id)
    {
        if (id is null or 0)
            return NotFound();

        var model = _repoProduct
            .FirstOrDefault(p => p.Id == id, include: nameof(ProductDTO.Category));
        if (model == null)
            return NotFound();

        return View(model);
    }

    [HttpPost, ActionName(nameof(Delete)), ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        if (id is null or 0)
            return NotFound();

        var model = _repoProduct.Find(id);
        if (model == null)
            return NotFound();

        RemoveImage(model.Image!);
        _repoProduct.Remove(model);
        _repoProduct.SaveChanges();

        TempData[Const.Success] = "Product deleted successfully";
        return RedirectToAction(nameof(Index));
    }

    #endregion Delete

    #region ControllerHelpers

    private void RemoveImage(string fileName)
    {
        var oldImage = string.Concat(_env.WebRootPath, Const.ProductImages, fileName);
        if (System.IO.File.Exists(oldImage))
            System.IO.File.Delete(oldImage);
    }

    #endregion ControllerHelpers
}

Rocky.Server/Views/Shared/_IndividualProductCard.cshtml
@using Rocky.Utility
@model Rocky.Models.Product.ProductDTO

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category!.Name!.Replace(' ', '_')">
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-start">@Model.Name</label></div>
            <div class="col-5"><label class="float-end"><span class="text-info h5">
                @($"{Model.Price:c0}")
            </span> / sqft</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3"
             src="@Const.ProductImages@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-12">
                <span class="badge p-2 border w-100" style="background-color: lavenderblush; color: #555">
                    @Model.Category!.Name
                </span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify" >
                <p>@Html.Raw(Model.ShortDescription)</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id"
                   class="btn btn-dark form-control btn-sm p-2" style="height: 40px">
                    View Details
                </a>
            </div>
        </div>
    </div>
</div>

Rocky.Server/Views/Shared/_Layout.cshtml
@using Rocky.Utility
@using Rocky.Models
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor

@{
    var carts = _httpContextAccessor.HttpContext!.Session
        .Get<IEnumerable<ShoppingCart>>(Const.SessionCartList);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Rocky.Server</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" >
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="//cdn.syncfusion.com/ej2/20.4.38/material.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/tile.png" width="40% "/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link ">Home</a>
                        </li>
                        @if (User.IsInRole(Const.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a asp-controller="Category" asp-action="Index" class="dropdown-item">Category</a>
                                    <a asp-controller="Product" asp-action="Index" class="dropdown-item">Product</a>
                                    <li><hr class="dropdown-divider"></li>
                                    <a asp-area="Identity" asp-page="/Account/Register" class="dropdown-item">Create Admin User</a>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Order/Inquiry Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a asp-controller="Inquiry" asp-action="Index" class="dropdown-item">Inquiry</a>
                                </ul>
                            </li>
                        } 
                        <li class="nav-item">
                            @if (carts is not null)
                            {
                                <a asp-controller="Cart" asp-action="Index" class="nav-link">
                                    <i class="fa-solid fa-cart-shopping"></i>(@carts.Count())
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link">
                                    <i class="fa-solid fa-cart-shopping"></i>(0)
                                </a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifycations"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container text-white-50">
            &copy; 2023 - Rocky
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="//cdn.syncfusion.com/ej2/20.4.38/dist/ej2.min.js"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Rocky.Server/Views/Shared/_Notifycations.cshtml
@using Rocky.Utility

@if (TempData.ContainsKey(Const.Success) || TempData.ContainsKey(Const.Error))
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.options = {
            "progressBar": true,
            "positionClass": "toast-bottom-right",
        };
    </script>

    @if (TempData.ContainsKey(Const.Success))
    {
        <script type="text/javascript">
            toastr.success('@TempData[Const.Success]');
        </script>
    } 
    else if (TempData.ContainsKey(Const.Error))
    {
        <script type="text/javascript">
            toastr.error('@TempData[Const.Error]');
        </script>
    }
}